insert into persona(id, nombre, direccion, edad) values (1, 'Willy0', 'Calderon0', 10)
insert into persona(id, nombre, direccion, edad) values (2, 'Willy1', 'Calderon1', 11)
insert into persona(id, nombre, direccion, edad) values (3, 'Willy2', 'Calderon2', 12)
insert into persona(id, nombre, direccion, edad) values (4, 'Willy3', 'Calderon3', 13)
insert into persona(id, nombre, direccion, edad) values (5, 'Willy4', 'Calderon4', 14)
insert into persona(id, nombre, direccion, edad) values (6, 'Willy5', 'Calderon5', 15)